<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Collection Settings
    |--------------------------------------------------------------------------
    |
    | These are the default settings for generated Postman collections.
    |
    */

    'collection_name' => env('POSTMAN_COLLECTION_NAME', config('app.name', 'Laravel') . ' API'),

    'description' => env('POSTMAN_COLLECTION_DESCRIPTION', 'API Documentation generated by Laravel Postman Generator'),

    /*
    |--------------------------------------------------------------------------
    | Output Directory
    |--------------------------------------------------------------------------
    |
    | Where the generated collection JSON files will be saved.
    |
    */

    'output_path' => storage_path('postman'),

    /*
    |--------------------------------------------------------------------------
    | Base URL
    |--------------------------------------------------------------------------
    |
    | The base URL to use in the collection. Use Postman variables for flexibility.
    |
    */

    'base_url' => '{{base_url}}',

    /*
    |--------------------------------------------------------------------------
    | Authentication Settings
    |--------------------------------------------------------------------------
    |
    | Configure default authentication behavior for the collection.
    |
    */

    'auth' => [
        // Default auth type: 'bearer', 'basic', 'apikey', 'oauth2', 'none'
        'type' => 'bearer',

        // Token variable name in Postman environment
        'token_variable' => 'auth_token',

        // Routes that provide authentication tokens (login endpoints)
        'login_routes' => [
            'login',
            'auth.login',
            'api.login',
            'auth/login',
            'api/auth/login',
        ],

        // Response field containing the token
        'token_response_field' => 'token',

        // Alternative token response fields to check
        'token_response_alternatives' => [
            'access_token',
            'data.token',
            'data.access_token',
            'user.token',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Sanctum Configuration
    |--------------------------------------------------------------------------
    |
    | Settings specific to Laravel Sanctum authentication.
    |
    */

    'sanctum' => [
        // Enable Sanctum-specific pre-request scripts
        'enabled' => true,

        // Store token automatically from login response
        'auto_store_token' => true,

        // Token expiry handling
        'handle_expiry' => true,

        // Token refresh endpoint (if applicable)
        'refresh_route' => null,
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Filtering
    |--------------------------------------------------------------------------
    |
    | Configure which routes to include or exclude from the collection.
    | Routes from ALL registered route files (api.php, candidate.php, etc.)
    | are automatically discovered regardless of where they are defined.
    |
    */

    'routes' => [
        // Include only routes matching these patterns
        'include' => [
            'api/*',
        ],

        // Exclude routes matching these patterns
        'exclude' => [
            '_ignition/*',
            'sanctum/*',
            'horizon/*',
            'telescope/*',
            'pulse/*',
            'api-documentation',
        ],

        // Middleware filters - include only routes with these middleware
        'middleware_include' => [],

        // Middleware filters - exclude routes with these middleware
        'middleware_exclude' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Pre-Request Scripts
    |--------------------------------------------------------------------------
    |
    | Default pre-request scripts for different scenarios.
    |
    */

    'scripts' => [
        // Pre-request script for authenticated routes
        'auth_pre_request' => <<<'JAVASCRIPT'
// Auto-set Bearer token from environment
const token = pm.environment.get("auth_token");
if (token) {
    pm.request.headers.add({
        key: "Authorization",
        value: "Bearer " + token
    });
}

// Check token expiry if stored
const tokenExpiry = pm.environment.get("token_expiry");
if (tokenExpiry && new Date() > new Date(tokenExpiry)) {
    console.warn("Token may be expired. Consider re-authenticating.");
}
JAVASCRIPT,

        // Post-response script for login routes to store token
        'login_post_response' => <<<'JAVASCRIPT'
// Store authentication token from response
if (pm.response.code === 200 || pm.response.code === 201) {
    const response = pm.response.json();

    // Try multiple possible token locations
    let token = response.token
        || response.access_token
        || (response.data && response.data.token)
        || (response.data && response.data.access_token)
        || (response.user && response.user.token);

    if (token) {
        pm.environment.set("auth_token", token);
        console.log("✓ Token stored successfully");

        // Store expiry if available
        const expiresIn = response.expires_in || response.ttl;
        if (expiresIn) {
            const expiry = new Date(Date.now() + (expiresIn * 1000));
            pm.environment.set("token_expiry", expiry.toISOString());
        }
    } else {
        console.warn("No token found in response");
    }
}
JAVASCRIPT,

        // Pre-request script for logout routes
        'logout_post_response' => <<<'JAVASCRIPT'
// Clear authentication token after logout
if (pm.response.code === 200 || pm.response.code === 204) {
    pm.environment.unset("auth_token");
    pm.environment.unset("token_expiry");
    console.log("✓ Token cleared successfully");
}
JAVASCRIPT,
    ],

    /*
    |--------------------------------------------------------------------------
    | Request Defaults
    |--------------------------------------------------------------------------
    |
    | Default headers and settings for all requests.
    |
    */

    'request_defaults' => [
        'headers' => [
            [
                'key' => 'Accept',
                'value' => 'application/json',
                'type' => 'text',
            ],
            [
                'key' => 'Content-Type',
                'value' => 'application/json',
                'type' => 'text',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | API Documentation Settings
    |--------------------------------------------------------------------------
    |
    | Configure the browser-based API documentation page.
    | Visit {base_url}/api-documentation to view your API docs.
    |
    */

    'documentation' => [
        // Enable or disable the documentation route
        'enabled' => true,

        // The URL path for the documentation page
        'route' => 'api-documentation',

        // Middleware to apply to the documentation route
        // Add 'auth' or custom middleware to restrict access
        'middleware' => ['web'],

        // Page title (defaults to collection_name if null)
        'title' => null,

        // Include route description from PHPDoc
        'include_phpdoc' => true,

        // Include validation rules as parameter descriptions
        'include_validation_rules' => true,

        // Include route middleware information
        'include_middleware' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Unique Features (No other package has these!)
    |--------------------------------------------------------------------------
    |
    | These features differentiate this package from all others.
    |
    */

    'features' => [
        // Auto-generate Postman test scripts for every endpoint
        // Tests include: status code, response time, JSON validation, auth checks
        'test_scripts' => true,

        // Generate example response bodies from API Resource classes
        // Parses your JsonResource toArray() to create realistic responses
        'example_responses' => true,

        // Generate realistic request bodies from Model Factory definitions
        // Parses your Factory definition() to create sample data using faker mappings
        'factory_data' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Grouping Options
    |--------------------------------------------------------------------------
    |
    | Available strategies for grouping routes in the collection.
    |
    */

    'grouping' => [
        // Default grouping strategy
        'default' => 'prefix',

        // Available strategies: 'prefix', 'controller', 'resource', 'name', 'middleware', 'tag'
        'strategies' => [
            'prefix' => \ProgrammersBeats\PostmanGenerator\Generators\PrefixGroupingStrategy::class,
            'controller' => \ProgrammersBeats\PostmanGenerator\Generators\ControllerGroupingStrategy::class,
            'resource' => \ProgrammersBeats\PostmanGenerator\Generators\ResourceGroupingStrategy::class,
            'name' => \ProgrammersBeats\PostmanGenerator\Generators\NameGroupingStrategy::class,
            'middleware' => \ProgrammersBeats\PostmanGenerator\Generators\MiddlewareGroupingStrategy::class,
            'tag' => \ProgrammersBeats\PostmanGenerator\Generators\TagGroupingStrategy::class,
        ],

        /*
        |----------------------------------------------------------------------
        | Custom Folder Names
        |----------------------------------------------------------------------
        |
        | Map route prefix segments or full paths to custom folder names.
        | These override the default Title Case naming in the collection
        | and documentation. Keys can be:
        |   - Full path: 'auth/pin' => 'PIN Management'
        |   - Segment:   'auth'     => 'Authentication'
        |
        | Example:
        |   'folder_names' => [
        |       'auth'      => 'Authentication',
        |       'auth/pin'  => 'PIN Management',
        |       'auth/2fa'  => '2FA Setup',
        |       'users'     => 'User Management',
        |   ],
        |
        */
        'folder_names' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Export Formats
    |--------------------------------------------------------------------------
    |
    | Configure the export format for the collection.
    |
    */

    'export' => [
        // Postman collection format version (2.1 recommended)
        'version' => '2.1.0',

        // Pretty print JSON output
        'pretty_print' => true,

        // Include environment file
        'include_environment' => true,

        // Environment variables to include
        'environment_variables' => [
            'base_url' => 'http://localhost:8000/api',
            'auth_token' => '',
            'token_expiry' => '',
        ],
    ],
];
